/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



/*
 * Steps for LED blink
 * *******************************************************************
 * 1) Enable the clock for GPIO in AHB1ENR RCC Register for GPIOA and GPIOC
 *
 * 2) Configure the Mode Register for GPIOA (PA5 in-bult LED)- Set to output
 * 3) Configure the output data register for GPIOA- set to output
 *
 * 4) Configure the Mode Register for GPIOC (PC13 in-bult Button)- Set to input
 * 5) Configure the input data register for GPIOC- set to input
 * ********************************************************************
 *
 * */


// Libraries
#include <stdint.h>

// Function Prototype
void init(void);   // for gpio init

// Base addresses for RCC and GPIOA (Inbuilt LED)
#define RCC_AHB1ENR      ((volatile uint32_t *) 0x40023830)  // RCC AHB1 peripheral clock enable register

#define GPIOA_MODER      ((volatile uint32_t *) 0x40020000)  // GPIOA mode register
#define GPIOA_ODR        ((volatile uint32_t *) 0x40020014)  // GPIOA output data register

// Base addresses for GPIOC (Inbuilt Button)
#define GPIOC_MODER      ((volatile uint32_t *) 0x40020800)  // GPIOC mode register
#define GPIOC_IDR        ((volatile uint32_t *) 0x40020810)  // GPIOC input data register



int main(void)
{
	init();    // Initialize the GPIOs and clock

	while(1)
	{
		if(!(*GPIOC_IDR & (1 << 13)))  // Check if the button (PC13) is pressed (logic low)
		{
			*GPIOA_ODR |= (1 << 5);  // Turn on the LED (PA5)

		}
		else
		{
			*GPIOA_ODR &= ~(1 << 5);  // Turn on the LED (PA5)
		}
	}
}


void init()
{
	*RCC_AHB1ENR      |= (1 << 0);      // Enable the AHB1ENR clock for GPIOA
	*RCC_AHB1ENR      |= (1 << 2);      // Enable the AHB1ENR clock for GPIOC

	*GPIOA_MODER      &= ~(3 << 10);    // Clear bits 10 and 11 (PA5 mode for LED)
	*GPIOA_MODER      |= (1 << 10);     // Set PA5 to output mode (binary '01' for general-purpose output)

	*GPIOC_MODER      &= ~(3 << 26);    // Clear bits 26 and 27 (PC13 mode for Button) // by default input
}

