/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Generating the PWM signal for controlling the LED brightness
 ******************************************************************************

 ******************************************************************************
 *@ Steps for Project
 * 1) Enable the Clock for GPIO and Timer in RCC
 * 2) Configure the GPIO Mode Register for PA5 (Alternate Function)
 * 3) Configure the Timer (TIM2) for PWM
 * 4) Create a Loop to Adjust Duty Cycle
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"

void Init(void);
void delay(void);
void Init()
{
    /* Enable the AHB1ENR clock for GPIOA */
    RCC->AHB1ENR |= (1 << 0);  // Enable GPIOA clock

    /* Enable the APB1ENR clock for TIM2 */
    RCC->APB1ENR |= (1 << 0);  // Enable TIM2 clock

    /* Peripheral Mode Configuration for GPIOA */
    GPIOA->MODER &= ~(0x3 << 10);   // Clear mode bits for PA5
    GPIOA->MODER |= (0x2 << 10);    // Set PA5 to Alternate Function Mode

    /* Alternate Function Configuration for PA5 (AF1 for TIM2_CH1) */
    GPIOA->AFR[0] &= ~(0xF << 20);  // Clear AFRL5
    GPIOA->AFR[0] |= (0x1 << 20);   // Set AFRL5 to AF1 (TIM2_CH1)

    /* Timer Register Configuration */
    TIM2->PSC = 10 - 1;             // Prescaler: divide clock by 10
    TIM2->ARR = 10000 - 1;          // Auto-reload value for a period of 1 ms (assuming 100 MHz clock, adjust as needed)
    TIM2->CCR1 = 1000 - 1;          // Duty cycle: 30% (CCR1 / ARR)

    /* Configure PWM Mode 1 for TIM2 Channel 1 */
    TIM2->CCMR1 &= ~(0x7 << 4);     // Clear OC1M bits
    TIM2->CCMR1 |= (0x6 << 4);      // Set OC1M to PWM mode 1
    TIM2->CCMR1 |= (1 << 3);        // Enable preload for CCR1

    /* Enable TIM2 Channel 1 Output */
    TIM2->CCER |= (1 << 0);         // Enable TIM2_CH1 output

    /* Enable Timer Counter */
    TIM2->CR1 |= (1 << 7);          // Enable Auto-reload Preload
    TIM2->CR1 |= (1 << 0);          // Enable TIM2
}

void delay()
{
	// Simple delay function (adjust for your clock speed for accuracy)
	for (volatile uint32_t j = 0; j < 500; j++) {
	// Empty loop for delay
	}
}

int main()
{
    Init(); // Initialize peripherals
    while(1)
    {
        for(uint32_t i = 0; i < 9999; i++)
        {
        	TIM2->CCR1 = i;
        	delay();
        }
        // Main loop, nothing to do here
    }
    return 0;
}
